### ISSUE TITLE
Java Versions

### ISSUE THREAD

**Issue by sclark-dev** [ich777/docker-minecraft-basic-server#3]
So, it's been announced that both Spigot and Paper for modded Minecraft servers are going to drop support for Java 8 when 1.17 is released. However, updating to Java 11 would break compatibility with servers pre-1.13.

It would be great to have a selector where we can choose Java 8 or 11.

**Comment by ich777** [comment]
I will be looking into it ASAP.
Eventually I can add another variable instead of 'basicjre' something like 'jre11'.
Would that be appropriate?

**Comment by sclark-dev** [comment]
That would be perfect. Another addition could be jre15 for those that are building servers/plugins based on the latest version of Java.

**Comment by ich777** [comment]
Now integrate, you can now select between 'basicjre' = jre8, 'jre11' = jre11 & 'jre15' = jre15 but please keep in mind if you change the runtime from one of the three preconfigured values to another one of the three values you have to delete the old runtime folder first and then the container will download the new version.

Please keep me updated if you experience any problems.
