### ISSUE TITLE
Runtime errors

### ISSUE THREAD

**Issue by sclark-dev** [ich777/docker-minecraft-basic-server#4]
So, there are a few errors that have cropped up.

1. When running the container using any JRE, there is an error that pops up.
`/opt/scripts/start-server.sh: line 48: /serverdata/serverfiles/runtime/{JRE}.tar.gz: Permission denied`
{JRE} being the version of runtime you're using. This doesn't break the container though.

2. Unless you are using basicjre, the server refuses to launch with an error regarding permissions.
`Cannot exec '/serverdata/serverfiles/runtime/jre11': Permission denied`
This happens consistently with either jre11, or jre15. The error takes place after the EULA test, so I'm assuming it's line 147 of start-server.sh?

As much as I would normally make a pull request, Docker is out of my realm of experience. Hopefully this helps track down those issues.

**Comment by ich777** [comment]
Are you sure that the runtime folder only has one folder in it?

**Comment by ich777** [comment]
There was a missing command in the container, please delete the runtime folder once more please and try again to restart the container.

**Comment by sclark-dev** [comment]
Ahh. I see what the issue was. Yes, the new code works on both JRE11 and JRE15. Thank you.
