### ISSUE TITLE
Issue with Authentication?

### ISSUE THREAD

**Issue by Chaos0344** [ich777/docker-minecraft-basic-server#5]
Not sure what else do to, as I'm not finding others with this issue.
Using a MC Eternal modpack, runs fine in windows, but when the files are copied into the server I'm getting a message about the authentication servers being down when I try to log in. Any chance I'm missing something?

Should also mention that the server ran fine with Vanilla, it is only having issues since switching to the modified jar, and I changed GAME_V to custom and am running the correct version of java 'basicjre'

Sorry if this is the wrong place for this. Not sure where else to post my issue.

**Comment by Chaos0344** [comment]
![2021-08-05 20_44_43-Log for_ MCEternal](https://user-images.githubusercontent.com/2448665/128443316-c1e18e69-0ccb-437c-9bda-d0ca3f785104.png)
Screenshot for refernce.

**Comment by ich777** [comment]
Do you run any blocking software on your network like PiHole or AdGuard?
Eventually something is blocking the connection to the Minecraft servers.
That's just a really wild guess...
Haven't seen that issue before.

**Comment by ich777** [comment]
@Chaos0344 I close this for now since it's working fine on my server.
