### ISSUE TITLE
Bungeecord servers do not shutdown properly

### ISSUE THREAD

**Issue by Unkn0wnCreator** [ich777/docker-minecraft-basic-server#7]
HI, 

First Very good work!

Could you maybe send "stop" and after that also "end" in the start.sh? Then bungeecord servers would also been shutdown properly.

**Comment by ich777** [comment]
But the server sends `stop` when you shut it done, if I add `end` too this would give users that are running other versions basically a error message when the container is stopped.

**Comment by ich777** [comment]
Closing this issue because of no response.
