### ISSUE TITLE
Support for custom launch commands

### ISSUE THREAD

**Issue by sclark-dev** [ich777/docker-minecraft-basic-server#9]
Recently Forge changed how their modded server gets launched. They don't offer JAR files anymore, and require you launch the server through a library command. The example one that is shipped with Forge is
`java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.1-39.0.63/unix_args.txt "$@"`

So unfortunately thanks to this change, it's impossible to deploy a 1.18 Forge server using this container. My hope is the addition of an environment variable that lets you override the default java command. This should be a hidden variable, similar to the RUNTIME_NAME.

**Comment by ich777** [comment]
@ff-sclark Thanks for the report, can you point me to a resource that explains that in more detail?

What should the variable look like? Do you need more variables, one to override how the container works currently, one for the jvm args.txt and one for the libraries?

Are the JVM args now in a textfile and also the libraries which the server as to use or am I wrong? I think the `user_jvm_args.txt` doesn't need to be in there and can be filled in with the variable `EXTRA_JVM_PARAMS` as it is now or would it be better to use also a file? If yes why? Are there already jvm arguments in this file?

As for the libraries should they be detected automatically, or need the updates to be done manually anyways?

Looking forward for your reply and thoughts.

**Comment by sclark-dev** [comment]
So, `user_jvm_args.txt` can probably go, and just pull from `EXTRA_JVM_PARAMS` like it does now. The default argument file just contains an explaination of `-Xmx` which is built into the container anyways.

The change could probably be as simple as adding an environment variable to the Dockerfile.
```
ENV JVM_COMMAND="${EXTRA_JVM_PARAMS} -Xmx${XMX_SIZE}M -Xms${XMS_SIZE}M -jar ${SERVER_DIR}/${JAR_NAME}.jar nogui ${GAME_PARAMS}"
```
This maintains backwards compatibility. Everything works the same, but can be overridden. This variable should probably be a hidden one like `RUNTIME_NAME`.

A simple change to the `start-server.sh` just so it's fed data from `JVM_COMMAND`.
```
screen -S Minecraft -L -Logfile ${SERVER_DIR}/masterLog.0 -d -m ${SERVER_DIR}/runtime/${RUNTIME_NAME}/bin/java ${JVM_COMMAND}
```

So for anyone currently using this container, there is no change that breaks anything. It should just work as a drop-in replacement, while allowing customization of the JVM arguments beyond what the container can do now.

**Comment by sclark-dev** [comment]
https://github.com/ich777/docker-minecraft-basic-server/issues/9#issuecomment-1025222629

The documentation on Forge is terrible. There isn't any official documentation on how the server launcher works, and this is just from looking at the scripts when I tried to set one up last night.

**Comment by ich777** [comment]
@ff-sclark thank you for the suggestions!

Please look at the new created `test` branch at this line: [Click](https://github.com/ich777/docker-minecraft-basic-server/blob/test/scripts/start-server.sh#L181)
Would this also be appropriate? Really don't want to change what is working now and this will also do the job I think. :)

If you are fine with that I will merge the `test` branch.

**Comment by sclark-dev** [comment]
That should work perfect. Hopefully this'll make it futureproof so it can handle any other changes to the launch command.

**Comment by ich777** [comment]
@ff-sclark thank you again, already merged!
Please update the container, container is already rebuilt.

**Comment by sclark-dev** [comment]
One issue I ran into is when the `start-server.sh` checks for the server JAR file when set to custom. There should be an exception for when `JVM_CUSTOM_COMMAND` is set.

**Comment by ich777** [comment]
@ff-sclark is there no jar file anymore or is it in a different location I think?

**Comment by ich777** [comment]
@ff-sclark I think this should do the job just fine: [Click](https://github.com/ich777/docker-minecraft-basic-server/blob/master/scripts/start-server.sh#L98)

Please report back what you think.

**Comment by sclark-dev** [comment]
> @ff-sclark I think this should do the job just fine: [Click](https://github.com/ich777/docker-minecraft-basic-server/blob/master/scripts/start-server.sh#L98)
> 
> Please report back what you think.

That should work. Yeah, they scrapped JARs entirely, and entirely rely on library loading.

**Comment by ich777** [comment]
@ff-sclark Thank you again!
Container is already rebuilt, if you got any further issues feel free to contact me again. :)

**Comment by thunderclap82** [comment]
@sclark-dev Did you get Minecraft 1.18+ working with the container? If so, can you give a short guide on what you did? I'm running this docker in Unraid, too, but I'm not as experienced with docker configurations and am struggling to get it going. Thanks.

**Comment by callumhauber** [comment]
> @sclark-dev Did you get Minecraft 1.18+ working with the container? If so, can you give a short guide on what you did? I'm running this docker in Unraid, too, but I'm not as experienced with docker configurations and am struggling to get it going. Thanks.

Hi, just came upon this so I thought I'd answer (in case anyone else ends up here)

When you click install for MinecraftBasicServer and enter the configuration page for the container, you need to add a new variable (scroll to the bottom and click `+ Add another Path, Port, Variable, Label or Device` and choose `Variable`). The name can be whatever, but `key` should be `JVM_CUSTOM_COMMAND` and `value` should be the Forge run command with the java/args stuff left out. In my case it's `@libraries/net/minecraftforge/forge/1.19.2-43.2.0/unix_args.txt nogui "$@"`, for example (I added `nogui` cause we're in a container so you don't care about that anyways, cause you have the web GUI). If there are JVM params you want to include, put them in front of the `@libraries` part.

You'll want to put the `libraries` folder from Forge into whatever folder you set for your container server files, and set your game version to `custom` and stuff. Hope this helps!
